### ISSUE TITLE
Should we filter reads before applying metapresence?

### ISSUE THREAD

**Issue by bhagavadgitadu22** [davidesangui/metapresence#2]
Hello,

I mapped my reads with minimap2 (default settings) on all high-quality viral MAGs from the IMG/VR database.

I tried applying metapresence after filtering the reads above 95% identity and 75% coverage: I got 32 presences with metapresence.

I tried the same without filtering the reads: I got 60 presences with metapresence.

Should I trust the results without filtering the reads? You decided not do it in your benchmarking paper was there a reason for that?

Martin

**Comment by davidesangui** [comment]
Hi,

How many reads do you lose when filtering? Perhaps what is happening is that MAGs identified as present with all reads are instead under the detection threshold (80 mapped reads by default) when you apply your filter.
Please let me know if that is the case.

Davide

**Comment by bhagavadgitadu22** [comment]
Here is the csv file recacapitulating the presences detected in samples with filtered reads (FR) or non-filtered-reads (NFR): [metapresence_differences_filtered_or_not.csv](https://github.com/user-attachments/files/16869198/metapresence_differences_filtered_or_not.csv)

Only 7 phages are absent in FR because the number of filtered reads falls below 80. The other 27 extra-presences are related to changes in BER and FUG values.

More surprisingly, 6 phages are present in FR but not in NFR because of changes BER and FUG values. I assume a drop in the BER value is possible because the number of reads is far greater without filtering.

Is my filtering too stringent? Or should I avoid filtering reads altogether?

**Comment by davidesangui** [comment]
Hi, 
sorry for the late reply, I was on vacation.

I looked at your data. There are indeed quite different BER values for a given genome in FR or NFR. 
I am not really into the implications (independently from metapresence) of filtering parameters for read mapping. I guess that the coverage threshold may significantly affect the metric values (especially BER). Considering that metapresence, when analyzing alignment results, only takes into account mapping positions and read length (therefore ignoring the actual alignment structure), BER may be overestimated in NFR. 
In general, I would be more confident with the results obtained using filtered reads, but this is a consideration that is not really dependent on metapresence. 
You may try to look at the depth distribution profiles of a given genome in FR o NFR; it may give some hints on what is actually happening to the coverage evenness between the two cases.  

Davide
