### ISSUE TITLE
Unpaired Flag Issue

### ISSUE THREAD

**Issue by shawnhoogstra** [davidesangui/metapresence#3]
Hello,

I've been playing around with unpaired data within metapresence. Every time I have tried to use this flag I get this error. Any help would be appreciated.

Traceback (most recent call last):
  File "databases/metapresence/metapresence.py", line 275, in <module>
    cov,ber,fug1,fug2,nreads=float(a[1]),float(a[3]),float(a[4]),float(a[5]),int(a[6])
ValueError: could not convert string to float: 'unpaired'

Thanks!

**Comment by davidesangui** [comment]
Hi!  

Thank you for pointing this problem out. When cleaning the code I must have forgotten to take the "unpaired case" into account.  
Now it should be fixed (I slightly modified line 275 of metapresence.py).  
Please let me know if there is any further problem.

Davide
